version: "3.8"

services:
  server:
    build: .
    env_file: .env
    depends_on:
      - database
    ports:
      - 3000:3000

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=Password123@
      - ACCEPT_EULA=Y
    volumes:
      - data:/var/opt/mssql

volumes:
  data:
